DROP DATABASE IF EXISTS gamifikator;
CREATE DATABASE IF NOT EXISTS gamifikator;
USE gamifikator;



CREATE TABLE USER_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  api_token VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PROPERTY_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  value INT NOT NULL,
  operator VARCHAR(10) NOT NULL,
  api_token VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE USER_BADGES_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  badge_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BADGE_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  api_token VARCHAR(100) NOT NULL,
  level INT,
  icon VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE RULE_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  api_token VARCHAR(100) NOT NULL,
  badge_id INT NOT NULL,
  property_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE APPLICATION_ENTITY
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  owner VARCHAR(50) NOT NULL,
  description VARCHAR(400),
	api_secret VARCHAR(100) UNIQUE,
  api_token VARCHAR(100) UNIQUE,
  is_deployed BOOL NOT NULL,
  PRIMARY KEY (id)
);
