version: '3'
services:
    appserver:
        build: ./images/payara
        container_name: appserver
        environment:
            - ADMIN_PASSWORD=admin
        restart: always
        ports:
            - "4848:4848"
            - "8080:8080"
        volumes:
            - ./deploy:/opt/payara5/deployments
        links:
            - db   
    db:
        build: ./images/mysql
        container_name: dbMysql
        environment:
            MYSQL_DATABASE: gamifikator
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data:/var/lib/mysql
            
volumes:
    data:
