DROP DATABASE IF EXISTS gamifikator;
CREATE OR REPLACE DATABASE gamifikator;
USE gamifikator;



CREATE TABLE USER
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  apitoken VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE USERBADGES
(
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  badgeId INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BADGE
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  apitoken VARCHAR(100) NOT NULL,
  level INT,
  icon VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE RULE
(
  id INT NOT NULL AUTO_INCREMENT,
  ruleName VARCHAR(50) NOT NULL,
  apitoken VARCHAR(100) NOT NULL,
  badgeId INT NOT NULL,
  propertyId INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE APPLICATION
(
  id INT NOT NULL AUTO_INCREMENT,
  ruleName VARCHAR(50) NOT NULL,
  creator VARCHAR(50) NOT NULL,
  owner_email VARCHAR(50) NOT NULL,
  description VARCHAR(400),
	apisecret VARCHAR(100) UNIQUE,
  apikey VARCHAR(100) UNIQUE,
  isDeployed BOOL NOT NULL,
  PRIMARY KEY (id)
);
